name: daraz_style_product_listing
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # main state management use 
  flutter_riverpod: ^3.0.3
  # route related 
  go_router: ^17.0.0


  # api services
  dio: ^5.9.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0

  # translator
  translator: ^1.0.4+1
  html: ^0.15.6

  # image related 
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.2.0

  # ui related
  permission_handler: ^12.0.1
  readmore: ^3.0.0
  skeletonizer: ^2.1.0+1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0 # dart run change_app_package_name:main com.new.package.name    
                                  #  if need only android --android
                                  #  if need only iod --ios



flutter:

  uses-material-design: true

# local all assets
  assets:
    - assets/fonts/
    - assets/images/

# local all font 
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf